version: '3.8'

services:
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/ssl:/etc/nginx/ssl:ro
        - ./public:/usr/share/nginx/html:ro
        - nginx-logs:/var/log/nginx
      depends_on:
        - app
      restart: unless-stopped
      networks:
        - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    expose:
      - "3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./public:/app/public
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - app-network

  

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge